encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("create/", views.create, name="create"),
    path("wiki/<str:title>", views.article, name="article"),
    path("random/", views.randompage, name="randompage"),
    path("wiki/", views.search_page, name="search")
]

wikinow/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls")),
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django import forms
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import render
import markdown2

from . import util


class NewPageForm(forms.Form):
    pagetitle = forms.CharField(max_length=50, label="Article name: ")
    pagecontent = forms.CharField(max_length=9000, label="Article content: ", widget=forms.Textarea)


def search_page(request):
    if request.method == "GET":
        query = request.GET.get("query")
        lst_entr = util.list_entries()
        matches = []
        while len(lst_entr) != 0:
            for i in lst_entr:
                if query == i or query == i.lower():
                    return render(request, "encyclopedia/wiki.html", {
                        "title": query,
                        "article": markdown2.markdown(util.get_entry(i))
                    })
                if query in i.lower() or query in i:
                    matches.append(i)
                    lst_entr.remove(i)
                    for a in lst_entr:
                        if a not in matches and query in a.lower():
                            matches.append(a)
                    print(matches)
                    print(lst_entr)
                    print(i)
                    return render(request, "encyclopedia/index.html", {
                        "tab_title": "Search",
                        "title": "Matches for " + query,
                        "entries": matches
                    })
            else:
                return render(request, "encyclopedia/wiki.html", {
                    "title": query,
                    "article": "Article with name " + query + " is not exist!"
                })


def index(request):
    print(util.list_entries())
    return render(request, "encyclopedia/index.html", {
        "tab_title": "Encyclopedia",
        "title": "All pages",
        "entries": util.list_entries(),
        "wiki_path": "wiki/"
    })


def article(request, title):
    return render(request, "encyclopedia/wiki.html", {
        "article": markdown2.markdown(util.get_entry(title)),
        "title": title
    })


def randompage(request):
    lenght = len(util.list_entries())
    r_entry, title = util.random_entry(lenght)
    return render(request, "encyclopedia/wiki.html", {
        "article": r_entry,
        "title": title
    })


def create(request):
    if request.method == "POST":
        form = NewPageForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data["pagetitle"]
            content = form.cleaned_data["pagecontent"]
            for a in util.list_entries():
                if a == title:
                    return render(request, "encyclopedia/create.html", {
                        "form": form
                    })
            return HttpResponseRedirect(reverse("encyclopedia:index"), {
                "save": util.save_entry(title, content)
            })
        else:
            return render(request, "encyclopedia/create.html", {
                "form": form
            })
    return render(request, "encyclopedia/create.html", {
        "form": NewPageForm(),
    })

encyclopedia/templates/encyclopedia/create.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia - Add Article
{% endblock %}

{% block body %}
    <h1>Add Page</h1>
    <form action="{% url 'encyclopedia:create' %}" method="post">
        {% csrf_token %}
        <table>
            <h6>Article name: </h6>
            {{ form.pagetitle }}
            <h6>Article content: </h6>
            {{ form.pagecontent }}
        </table>
        <input type="submit" value="Add">
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ tab_title }}
{% endblock %}

{% block body %}
    <h1>{{ title }}</h1>
    <div class="border-bottom"></div>
    <ul>
        {% for entry in entries %}
            <li>
                <a href="{{ wiki_path }}{{ entry }}">{{ entry }}<a/>
            </li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>WikiNow</h2>
                <form action="{% url 'encyclopedia:search' %}" method="get">
                    <table>
                        <input id="search" name="query" type="text" class="form-control" placeholder="Search" aria-label="Search">
                    </table>
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:create' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:randompage' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>
    </body>
</html>

encyclopedia/templates/encyclopedia/wiki.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
    <div>
        <h1> {{ title }} </h1>
        <div class="border-bottom"></div>
        <article>
            <pre>
                {{ article|safe }}
            </pre>
        </article>
    </div>
{% endblock %}